### ISSUE TITLE
数据加密的问题

### ISSUE THREAD

**Issue by JiXiaomai** [ca1e/SMM2CourseDecryptorNet#1]
如果需要对数据重新加密需要使用哪些函数和参数

**Comment by ca1e** [comment]
> 如果需要对数据重新加密需要使用哪些函数和参数

我参考的项目貌似并没有实现重新加密，所以我也没有实现相关功能
如果你能提供相关参考代码我会抽时间添加上的

**Comment by ca1e** [comment]
https://github.com/jonbarrow/partrick
这个挺全的可以研究一下

**Comment by ca1e** [comment]
目前已经支持加密/解密地图数据，具体代码查看项目例子。期待杰克西奥麦的新研究！
